// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsn-SEKV2o4KNOw2woobbnIA_qcoHnrnU',
    appId: '1:1073123987741:web:3833377cade034e46c91f4',
    messagingSenderId: '1073123987741',
    projectId: 'shopping-app-382c2',
    authDomain: 'shopping-app-382c2.firebaseapp.com',
    storageBucket: 'shopping-app-382c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNcSe0ofKETlPA_jJ9ksOd1SZTh1lS7io',
    appId: '1:1073123987741:android:b74615a6c824ad6a6c91f4',
    messagingSenderId: '1073123987741',
    projectId: 'shopping-app-382c2',
    storageBucket: 'shopping-app-382c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUHYJW1IBPKsMDIbB45N9Zu0TyT-tvIIQ',
    appId: '1:1073123987741:ios:a442418778b01c986c91f4',
    messagingSenderId: '1073123987741',
    projectId: 'shopping-app-382c2',
    storageBucket: 'shopping-app-382c2.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );
}
